//! Common glue code between Rust and JNI, used in autogenerated jni-bindgen glue code.
//!
//! See also the [Android JNI tips](https://developer.android.com/training/articles/perf-jni) documentation as well as the
//! [Java Native Interface Specification](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/jniTOC.html).

// Re-export a few things such that we have a consistent name for them in autogenerated glue code wherever we go.
#[doc(hidden)]
pub use ::jni_sys;
#[doc(hidden)]
pub use ::std;

use jni_sys::*;



mod __jni_bindgen;
mod gen_vm;
mod string_chars;
mod throwable_type;


pub use string_chars::*;
pub use throwable_type::*;

